<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Model" nsURI="http:///Model.ecore" nsPrefix="Model">
  <eClassifiers xsi:type="ecore:EClass" name="funcionario">
    <eOperations name="registrofuncionario" ordered="false" lowerBound="1"/>
    <eOperations name="excluifuncionario" ordered="false" lowerBound="1"/>
    <eOperations name="atualizafuncionario" ordered="false" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idfuncionario" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nome" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="terminal">
    <eOperations name="registraacesso" ordered="false" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idterminal" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idfuncionario" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="horalogin" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idbiblioteca" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="biblioteca">
    <eOperations name="registrabiblioteca" ordered="false" lowerBound="1"/>
    <eOperations name="excluibiblioteca" ordered="false" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idbiblioteca" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="exemplar">
    <eOperations name="registraexemplar" ordered="false" lowerBound="1"/>
    <eOperations name="excluiexemplar" ordered="false" lowerBound="1"/>
    <eOperations name="bloqueiaexemplar" ordered="false" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idexemplar" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idpublicacao" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bloqueado" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idbiblioteca" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="emprestimo">
    <eOperations name="realizaemprestimo" ordered="false" lowerBound="1"/>
    <eOperations name="realizadevolucao" ordered="false" lowerBound="1"/>
    <eOperations name="calculamulta" ordered="false" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idemprestimo" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idexemplar" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="registrousuario" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="datadevolucao" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idbiblioteca" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="publicacao">
    <eOperations name="registrapublicacao" ordered="false" lowerBound="1"/>
    <eOperations name="excluipublicacao" ordered="false" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idpublicacao" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="autor" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="assunto" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idbiblioteca" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="livro" eSuperTypes="#//publicacao"/>
  <eClassifiers xsi:type="ecore:EClass" name="periodico" eSuperTypes="#//publicacao"/>
  <eClassifiers xsi:type="ecore:EClass" name="tese" eSuperTypes="#//publicacao"/>
  <eClassifiers xsi:type="ecore:EClass" name="manual" eSuperTypes="#//publicacao"/>
  <eClassifiers xsi:type="ecore:EClass" name="usuario">
    <eOperations name="registrausuario" ordered="false" lowerBound="1"/>
    <eOperations name="excluiusuario" ordered="false" lowerBound="1"/>
    <eOperations name="atualizausuario" ordered="false" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="registro" ordered="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nome" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sobrenome" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pronome" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="datanascimento" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cpf" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fone" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endereco" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cep" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cidade" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="estado" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pais" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="aluno" eSuperTypes="#//usuario">
    <eOperations name="registraaluno" ordered="false" lowerBound="1"/>
    <eOperations name="excluialuno" ordered="false" lowerBound="1"/>
    <eOperations name="atualizaaluno" ordered="false" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="curso" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="professor" eSuperTypes="#//usuario">
    <eOperations name="registraprofessor" ordered="false" lowerBound="1"/>
    <eOperations name="excluiprofessor" ordered="false" lowerBound="1"/>
    <eOperations name="atualizaprofessor" ordered="false" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instituicao" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
  </eClassifiers>
</ecore:EPackage>
